#!/usr/bin/env python3
"""Keeps the docs a linked graph (the repo root is also an Obsidian vault; the links work on GitHub too).

1. Regenerates docs/CODE_MAP.md: every source/build file, grouped by area, with the first sentence of its own
   javadoc or header comment.
2. In README.md, CLAUDE.md and docs/*.md, turns the first unlinked mention of another doc (RULES_MATRIX, DECISIONS,
   debug-log, ...) or of a repo file/class in backticks (`KeyCpsModule`, `scripts/smoke.sh`) into a relative Markdown
   link. Headings, fenced code and existing links are left alone. Idempotent.

usage: scripts/docs-graph.py [--check]   (--check: exit 1 if anything would change)
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CODE_EXT = (".java", ".kts", ".json", ".py", ".sh", ".properties")
SKIP = ("gradle/wrapper/", ".github/")
DOCS = ["PLAN", "ARCHITECTURE", "DECISIONS", "PROGRESS", "RULES_MATRIX", "COMPAT_MATRIX", "FEATHER", "THIRD_PARTY",
        "PLUGIN_API", "CODE_MAP", "PERF", "PRISM", "FEATHER_CHECKLIST", "debug-log"]


def repo_files():
    out = subprocess.run(["git", "ls-files", "--cached", "--others", "--exclude-standard"], cwd=ROOT,
                         capture_output=True, text=True, check=True).stdout.split("\n")
    return sorted(f for f in out if f and os.path.exists(os.path.join(ROOT, f)))


def summary(path):
    """First sentence of the type's javadoc (Java) or of the leading comment block (scripts, Gradle files)."""
    try:
        text = open(os.path.join(ROOT, path), encoding="utf-8", errors="replace").read()
    except OSError:
        return ""
    if path.endswith(".java"):
        m = re.search(r"/\*\*(.*?)\*/\s*(?:@[\w.]+(?:\([^)]*\))?\s*|//\?[^\n]*\n\s*|/\*[^*].*?\*/\s*)*"
                      r"(?:public\s+|final\s+|abstract\s+)*(?:class|interface|enum)\b", text, re.S)
        if not m:
            return ""
        doc = re.sub(r"^\s*\*\s?", "", m.group(1), flags=re.M)
        doc = re.sub(r"\{@(?:link|code)\s+([^}]*)\}", r"\1", doc)
        doc = " ".join(doc.replace("<p>", " ").split())
    elif path.endswith((".py", ".sh", ".kts", ".properties")):
        lines = []
        for line in text.split("\n")[:12]:
            s = line.strip()
            if s.startswith("#!") or not s:
                if lines:
                    break
                continue
            if s.startswith(("#", "//")):
                lines.append(s.lstrip("#/ ").strip())
            elif s.startswith(('"""', "'''")):
                lines.append(s.strip("\"' "))
            else:
                break
        doc = " ".join(lines)
    else:
        return ""
    doc = re.split(r"(?<=[.!?])\s", doc, maxsplit=1)[0]
    return doc if len(doc) <= 160 else doc[:157].rstrip() + "..."


def area(path):
    parts = path.split("/")
    if len(parts) == 1:
        return "Build and repo root"
    top = parts[0]
    if path.endswith(".java"):
        pkg = "/".join(parts[parts.index("java") + 1:-1]).replace("/", ".") if "java" in parts else top
        test = "src/test/" in path
        return f"{top}{' tests' if test else ''} · `{pkg}`"
    if top in ("fabric", "legacy", "core", "api", "addons"):
        return f"{top} · build and resources"
    return top


def gen_code_map(files):
    groups = {}
    for f in files:
        if not f.endswith(CODE_EXT) or f.startswith(SKIP) or f.endswith("Untitled.base"):
            continue
        groups.setdefault(area(f), []).append(f)
    order = ["Build and repo root", "api", "core", "fabric", "legacy", "addons", "scripts"]
    keys = sorted(groups, key=lambda k: (next((i for i, o in enumerate(order) if k.startswith(o)), 99), k))
    out = ["# Code map", "",
           "Every source and build file with the first sentence of its own documentation. Generated by",
           "[`scripts/docs-graph.py`](../scripts/docs-graph.py), so do not edit by hand. Start at [README](../README.md);",
           "for how the pieces fit see [ARCHITECTURE](ARCHITECTURE.md).", ""]
    for k in keys:
        out.append(f"## {k}")
        out.append("")
        for f in groups[k]:
            s = summary(f)
            out.append(f"- [{os.path.basename(f)}](../{f})" + (f": {s}" if s else ""))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def link_docs(text, here, files, by_name):
    """Links first mentions; `here` is the doc's repo-relative path."""
    base = os.path.dirname(here)
    rel = lambda target: os.path.relpath(target, base or ".").replace(os.sep, "/")
    done = set(re.findall(r"\]\(([^)#]+)", text))  # targets already linked from this doc
    done = {os.path.normpath(os.path.join(base, t)).replace(os.sep, "/") for t in done}
    done.add(here)
    lines, fence = text.split("\n"), False

    def target_for_code(token):
        tok = token.strip()
        if tok.startswith(("~", "/", "http")) or "<" in tok or " " in tok:
            return None
        if "..." in tok:  # abbreviated path like core/.../gui/Icons.java
            suffix = tok.split("...")[-1].lstrip("/")
            hits = [f for f in files if f.endswith("/" + suffix) or f == suffix]
            return hits[0] if len(hits) == 1 else None
        if tok in files:
            return tok
        name = tok if "." in os.path.basename(tok) else tok + ".java"
        hits = by_name.get(name, [])
        return hits[0] if len(hits) == 1 else None

    for i, line in enumerate(lines):
        if line.startswith("```"):
            fence = not fence
            continue
        if fence or line.startswith("#"):
            continue

        # 1) doc names in prose or code spans: `docs/RULES_MATRIX.md`, RULES_MATRIX, DECISIONS D-018, debug-log
        def doc_repl(m):
            name = m.group("name")
            target = "README.md" if name == "README" else "CLAUDE.md" if name == "CLAUDE" else f"docs/{name}.md"
            if target in done or not os.path.exists(os.path.join(ROOT, target)):
                return m.group(0)
            done.add(target)
            label = m.group("label") or name
            return f"[{label}]({rel(target)})"

        names = "|".join(re.escape(n) for n in DOCS + ["README", "CLAUDE"])
        doc_re = re.compile(r"(?<![\w/\[`.-])`?(?:docs/)?(?P<label>(?P<name>" + names + r")(?:\.md)?)`?(?![\w\]]|\.md\]|\]\()")

        # 2) repo files/classes in code spans: `KeyCpsModule`, `scripts/smoke.sh`, `core/.../gui/Icons.java`
        def code_repl(m):
            t = target_for_code(m.group(1))
            if not t or t in done:
                return m.group(0)
            done.add(t)
            return f"[`{m.group(1)}`]({rel(t)})"

        # Work only on the parts of the line outside existing links.
        parts = re.split(r"(\[[^\]]*\]\([^)]*\))", line)
        for j in range(0, len(parts), 2):
            seg = re.sub(r"(?<!\[)`([^`\n]+)`(?!\])", lambda m: code_repl(m), parts[j])
            pieces = re.split(r"(\[[^\]]*\]\([^)]*\))", seg)
            for q in range(0, len(pieces), 2):
                pieces[q] = doc_re.sub(doc_repl, pieces[q])
            parts[j] = "".join(pieces)
        lines[i] = "".join(parts)
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv
    files = repo_files()
    by_name = {}
    for f in files:
        by_name.setdefault(os.path.basename(f), []).append(f)
    changed = []
    targets = {"docs/CODE_MAP.md": gen_code_map(files)}
    files_with_map = sorted(set(files) | {"docs/CODE_MAP.md"})
    by_name.setdefault("CODE_MAP.md", ["docs/CODE_MAP.md"])
    for doc in ["README.md", "CLAUDE.md"] + sorted(f for f in files_with_map if f.startswith("docs/") and f.endswith(".md")):
        if doc == "docs/CODE_MAP.md" or not os.path.exists(os.path.join(ROOT, doc)):
            continue
        old = open(os.path.join(ROOT, doc), encoding="utf-8").read()
        targets[doc] = link_docs(old, doc, files_with_map, by_name)
    for path, new in targets.items():
        full = os.path.join(ROOT, path)
        old = open(full, encoding="utf-8").read() if os.path.exists(full) else None
        if old != new:
            changed.append(path)
            if not check:
                open(full, "w", encoding="utf-8").write(new)
    print(("would change: " if check else "updated: ") + (", ".join(changed) or "nothing"))
    sys.exit(1 if check and changed else 0)


if __name__ == "__main__":
    main()
